# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='driver_license_copy_down',
            new_name='driver_license_down',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='driver_license_copy_top',
            new_name='driver_license_top',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='national_id_copy_down',
            new_name='national_id_down',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='national_id_copy_top',
            new_name='national_id_top',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='road_worthiness_certificate_down',
            field=models.ImageField(default=1, upload_to='users/road_worthiness_certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='road_worthiness_certificate_top',
            field=models.ImageField(default=1, upload_to='users/road_worthiness_certificate'),
            preserve_default=False,
        ),
    ]
