# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_auto_20170908_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies_logo/'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='driver_license_down',
            field=models.ImageField(blank=True, null=True, upload_to='users/driver_license'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='driver_license_top',
            field=models.ImageField(blank=True, null=True, upload_to='users/driver_license'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national_id_down',
            field=models.ImageField(blank=True, null=True, upload_to='users/national_id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national_id_top',
            field=models.ImageField(blank=True, null=True, upload_to='users/national_id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='road_worthiness_certificate_down',
            field=models.ImageField(blank=True, null=True, upload_to='users/road_worthiness_certificate'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='road_worthiness_certificate_top',
            field=models.ImageField(blank=True, null=True, upload_to='users/road_worthiness_certificate'),
        ),
    ]
