# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_auto_20170908_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national_id_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
