# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_auto_20170908_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
