# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 18:38
from __future__ import unicode_literals

import claim.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceCompany', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=claim.models.get_image_filename, verbose_name='Image')),
                ('claim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='claim.Claim')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.Claim')),
            ],
        ),
    ]
